# Site Settings
title: Start Jekyll
email: codyalantaylor@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: ""
url: "http://localhost:8000"
twitter_username: OKCody_
github_username:  OKCody
# Build Settings
include: ['_pages']
kramdown:
  input: GFM